config/routes.rb
Plusdollar2::Application.routes.draw do
  resources :users

  resources :post2s

  resources :posts

 

  resources :links

  resources :votes
  
   resources :users
  
  
  resources :posts, :users
  
  root :to => 'users#index'

  

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :date, :description, :link
end

app/models/post2.rb
class Post2 < ActiveRecord::Base
  belongs_to :user
  attr_accessible :date, :text, :title, :user_id, :user
  validates :text, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :username
  validates :email, :presence => true
  validates :name, :presence => true
  validates :username, :presence => true
  #validates_presence_of :email, :name, :username
  has_many :posts
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :answer, :date, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  # GET /links
  # GET /links.json
  def index
    @links = Link.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @links }
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/new
  # GET /links/new.json
  def new
    @link = Link.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = Link.find(params[:id])
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(params[:link])

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render json: @link, status: :created, location: @link }
      else
        format.html { render action: "new" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.json
  def update
    @link = Link.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/post2s_controller.rb
class Post2sController < ApplicationController
  # GET /post2s
  # GET /post2s.json
  def index
    @post2s = Post2.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @post2s }
    end
  end

  # GET /post2s/1
  # GET /post2s/1.json
  def show
    @post2 = Post2.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post2 }
    end
  end

  # GET /post2s/new
  # GET /post2s/new.json
  def new
    @post2 = Post2.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post2 }
    end
  end

  # GET /post2s/1/edit
  def edit
    @post2 = Post2.find(params[:id])
  end

  # POST /post2s
  # POST /post2s.json
  def create
    @post2 = Post2.new(params[:post2])
    
    
    respond_to do |format|
      if @post2.save
        format.html { redirect_to @post2, notice: 'Post2 was successfully created.' }
        format.json { render json: @post2, status: :created, location: @post2 }
      else
        format.html { render action: "new" }
        format.json { render json: @post2.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /post2s/1
  # PUT /post2s/1.json
  def update
    @post2 = Post2.find(params[:id])

    respond_to do |format|
      if @post2.update_attributes(params[:post2])
        format.html { redirect_to @post2, notice: 'Post2 was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post2.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post2s/1
  # DELETE /post2s/1.json
  def destroy
    @post2 = Post2.find(params[:id])
    @post2.destroy

    respond_to do |format|
      format.html { redirect_to post2s_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @votes }
    end
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
    @vote = Vote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vote }
    end
  end

  # GET /votes/new
  # GET /votes/new.json
  def new
    @vote = Vote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vote }
    end
  end

  # GET /votes/1/edit
  def edit
    @vote = Vote.find(params[:id])
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(params[:vote])

    respond_to do |format|
      if @vote.save
        format.html { redirect_to @vote, notice: 'Vote was successfully created.' }
        format.json { render json: @vote, status: :created, location: @vote }
      else
        format.html { render action: "new" }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /votes/1
  # PUT /votes/1.json
  def update
    @vote = Vote.find(params[:id])

    respond_to do |format|
      if @vote.update_attributes(params[:vote])
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote = Vote.find(params[:id])
    @vote.destroy

    respond_to do |format|
      format.html { redirect_to votes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/post2s_helper.rb
module Post2sHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plusdollar2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1>Listing links</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Link</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @links.each do |link| %>
  <tr>
    <td><%= link.description %></td>
    <td><%= link.link %></td>
    <td><%= link.date %></td>
    <td><%= link_to 'Show', link %></td>
    <td><%= link_to 'Edit', edit_link_path(link) %></td>
    <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @link.description %>
</p>

<p>
  <b>Link:</b>
  <%= @link.link %>
</p>

<p>
  <b>Date:</b>
  <%= @link.date %>
</p>


<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/pledges/_form.html.erb
<%= form_for(@pledge) do |f| %>
  <% if @pledge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pledge.errors.count, "error") %> prohibited this pledge from being saved:</h2>

      <ul>
      <% @pledge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :issue_url %><br />
    <%= f.text_field :issue_url %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :issue_title %><br />
    <%= f.text_field :issue_title %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :decimal %><br />
    <%= f.text_field :decimal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pledges/edit.html.erb
<h1>Editing pledge</h1>

<%= render 'form' %>

<%= link_to 'Show', @pledge %> |
<%= link_to 'Back', pledges_path %>

app/views/pledges/index.html.erb
<h1>Listing pledges</h1>

<table>
  <tr>
    <th>Issue url</th>
    <th>String</th>
    <th>Issue title</th>
    <th>String</th>
    <th>Amount</th>
    <th>Decimal</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pledges.each do |pledge| %>
  <tr>
    <td><%= pledge.issue_url %></td>
    <td><%= pledge.string %></td>
    <td><%= pledge.issue_title %></td>
    <td><%= pledge.string %></td>
    <td><%= pledge.amount %></td>
    <td><%= pledge.decimal %></td>
    <td><%= link_to 'Show', pledge %></td>
    <td><%= link_to 'Edit', edit_pledge_path(pledge) %></td>
    <td><%= link_to 'Destroy', pledge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pledge', new_pledge_path %>

app/views/pledges/new.html.erb
<h1>New pledge</h1>

<%= render 'form' %>

<%= link_to 'Back', pledges_path %>

app/views/pledges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Issue url:</b>
  <%= @pledge.issue_url %>
</p>

<p>
  <b>String:</b>
  <%= @pledge.string %>
</p>

<p>
  <b>Issue title:</b>
  <%= @pledge.issue_title %>
</p>

<p>
  <b>String:</b>
  <%= @pledge.string %>
</p>

<p>
  <b>Amount:</b>
  <%= @pledge.amount %>
</p>

<p>
  <b>Decimal:</b>
  <%= @pledge.decimal %>
</p>


<%= link_to 'Edit', edit_pledge_path(@pledge) %> |
<%= link_to 'Back', pledges_path %>

app/views/post2s/_form.html.erb
<%= form_for(@post2) do |f| %>
  <% if @post2.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post2.errors.count, "error") %> prohibited this post2 from being saved:</h2>

      <ul>
      <% @post2.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.collection_select :user_id, User.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post2s/edit.html.erb
<h1>Editing post2</h1>

<%= render 'form' %>

<%= link_to 'Show', @post2 %> |
<%= link_to 'Back', post2s_path %>

app/views/post2s/index.html.erb
<h1>Listing post2s</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Date</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @post2s.each do |post2| %>
  <tr>
    <td><%= post2.title %></td>
    <td><%= post2.text %></td>
    <td><%= post2.date %></td>
    <td><%= post2.user.name %></td>
    <td><%= link_to 'Show', post2 %></td>
    <td><%= link_to 'Edit', edit_post2_path(post2) %></td>
    <td><%= link_to 'Destroy', post2, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post2', new_post2_path %>

app/views/post2s/new.html.erb
<h1>New post2</h1>

<%= render 'form' %>

<%= link_to 'Back', post2s_path %>

app/views/post2s/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post2.title %>
</p>

<p>
  <b>Text:</b>
  <%= @post2.text %>
</p>

<p>
  <b>Date:</b>
  <%= @post2.date %>
</p>

<p>
  <b>User:</b>
  <%= @post2.user.name %>
</p>


<%= link_to 'Edit', edit_post2_path(@post2) %> |
<%= link_to 'Back', post2s_path %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <% f.collection_select :user, User.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Date</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.text %></td>
    <td><%= post.date %></td>
    <td><%= pledge.user.name %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Text:</b>
  <%= @post.text %>
</p>

<p>
  <b>Date:</b>
  <%= @post.date %>
</p>

<p>
	<b>User:</b>
	<%= @post.user_name %>
</p>	
	
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Username</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.username %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_field :answer %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<h1>Listing votes</h1>

<table>
  <tr>
    <th>Answer</th>
    <th>Name</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @votes.each do |vote| %>
  <tr>
    <td><%= vote.answer %></td>
    <td><%= vote.name %></td>
    <td><%= vote.date %></td>
    <td><%= link_to 'Show', vote %></td>
    <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
    <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New vote</h1>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Answer:</b>
  <%= @vote.answer %>
</p>

<p>
  <b>Name:</b>
  <%= @vote.name %>
</p>

<p>
  <b>Date:</b>
  <%= @vote.date %>
</p>


<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>